[package]
name = "types"
version = "0.0.1"
edition = "2021"

[dependencies]
aws-sdk-dynamodb.workspace = true
chrono.workspace = true
serde.workspace = true
thiserror.workspace = true
uuid.workspace = true

[dev-dependencies]
serde_json.workspace = true