name: 'UI: Lint'

on:
  pull_request:
    branches:
      - develop
      - release/*

env:
  NODE_VERSION: '20.x'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm install -g pnpm

      - name: pnpm install
        working-directory: ./plugin
        run: pnpm install

      - name: Run lint
        working-directory: ./plugin
        run: pnpm run lint
